name: instagram_private_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.3'
dependencies: { crypto: ^3.0.2, dio: ^4.0.6, dio_cookie_manager: ^2.0.0, hex: ^0.2.0, image: ^3.2.0, intl: ^0.17.0, json_annotation: ^4.6.0, uuid: ^3.0.6}
dev_dependencies: {build_runner: ^2.2.0, json_serializable: ^6.3.1, pedantic: ^1.11.1, test: ^1.21.4}


